laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('a-empresa/{slug?}', 'EmpresaController@index')->name('empresa');
    Route::get('areas-de-atuacao/{areaDeAtuacao?}', 'AreasDeAtuacaoController@index')->name('areas-de-atuacao');
    Route::get('responsabilidade-social', 'ResponsabilidadeSocialController@index')->name('responsabilidade-social');
    Route::get('tecnologias/{tecnologia?}', 'TecnologiasController@index')->name('tecnologias');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe-conosco');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en' || $idioma == 'es') {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('trabalhe-conosco', 'TrabalheConoscoController', ['only' => ['index', 'update']]);
		Route::resource('tecnologias', 'TecnologiasController');
        Route::resource('areas-de-atuacao', 'AreasDeAtuacaoController');
		Route::resource('areas-de-atuacao.subcategorias', 'AreasDeAtuacaoSubcategoriasController');
		Route::resource('responsabilidade-social', 'ResponsabilidadeSocialController', ['only' => ['index', 'update']]);
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
		Route::resource('missao-e-visao', 'MissaoEVisaoController', ['only' => ['index', 'update']]);
		Route::resource('garantia-de-qualidade', 'GarantiaDeQualidadeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AreasDeAtuacaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeAtuacaoRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeAtuacao;

class AreasDeAtuacaoController extends Controller
{
    public function index()
    {
        $registros = AreaDeAtuacao::ordenados()->get();

        return view('painel.areas-de-atuacao.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.areas-de-atuacao.create');
    }

    public function store(AreasDeAtuacaoRequest $request)
    {
        try {

            $input = $request->all();
            $input['capa'] = AreaDeAtuacao::uploadCapa();
            $input['imagem'] = AreaDeAtuacao::uploadImagem();

            AreaDeAtuacao::create($input);
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeAtuacao $registro)
    {
        return view('painel.areas-de-atuacao.edit', compact('registro'));
    }

    public function update(AreasDeAtuacaoRequest $request, AreaDeAtuacao $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['capa'])) $input['capa'] = AreaDeAtuacao::uploadCapa();
            if (isset($input['imagem'])) $input['imagem'] = AreaDeAtuacao::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeAtuacao $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AreasDeAtuacaoSubcategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeAtuacaoSubcategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeAtuacao;
use App\Models\AreaDeAtuacaoSubcategoria;

class AreasDeAtuacaoSubcategoriasController extends Controller
{
    public function index(AreaDeAtuacao $areaDeAtuacao)
    {
        $registros = AreaDeAtuacaoSubcategoria::area($areaDeAtuacao->id)
            ->ordenados()->get();

        return view('painel.areas-de-atuacao.subcategorias.index', compact('areaDeAtuacao', 'registros'));
    }

    public function create(AreaDeAtuacao $areaDeAtuacao)
    {
        return view('painel.areas-de-atuacao.subcategorias.create', compact('areaDeAtuacao'));
    }

    public function store(AreaDeAtuacao $areaDeAtuacao, AreasDeAtuacaoSubcategoriasRequest $request)
    {
        try {

            $input = $request->all();

            $areaDeAtuacao->subcategorias()->create($input);

            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        return view('painel.areas-de-atuacao.subcategorias.edit', compact('areaDeAtuacao', 'registro'));
    }

    public function update(AreasDeAtuacaoSubcategoriasRequest $request, AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);
            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Banner::uploadImagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = Banner::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/GarantiaDeQualidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\GarantiaDeQualidadeRequest;
use App\Http\Controllers\Controller;

use App\Models\GarantiaDeQualidade;

class GarantiaDeQualidadeController extends Controller
{
    public function index()
    {
        $registro = GarantiaDeQualidade::first();

        return view('painel.garantia-de-qualidade.edit', compact('registro'));
    }

    public function update(GarantiaDeQualidadeRequest $request, GarantiaDeQualidade $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = GarantiaDeQualidade::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.garantia-de-qualidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/MissaoEVisaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\MissaoEVisaoRequest;
use App\Http\Controllers\Controller;

use App\Models\MissaoEVisao;

class MissaoEVisaoController extends Controller
{
    public function index()
    {
        $registro = MissaoEVisao::first();

        return view('painel.missao-e-visao.edit', compact('registro'));
    }

    public function update(MissaoEVisaoRequest $request, MissaoEVisao $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = MissaoEVisao::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.missao-e-visao.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/NewsletterController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Newsletter;

class NewsletterController extends Controller
{
    public function index()
    {
        $emails = Newsletter::orderBy('email', 'ASC')->paginate(20);

        return view('painel.newsletter.index', compact('emails'));
    }

    public function destroy(Newsletter $email)
    {
        try {

            $email->delete();
            return redirect()->route('painel.newsletter.index')->with('success', 'E-mail excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir e-mail: '.$e->getMessage()]);

        }
    }

    public function exportar()
    {
        $file = 'liotecnica-newsletter_'.date('d-m-Y_His');

        \Excel::create($file, function($excel) {
            $excel->sheet('emails', function($sheet) {
                $sheet->fromModel(Newsletter::orderBy('email', 'ASC')->get(['nome', 'email']));
            });
        })->download('csv');
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use App\Helpers\CropImage;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/areas-de-atuacao/imagens/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }

}

laravel/app/Http/Controllers/Painel/QuemSomosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\QuemSomosRequest;
use App\Http\Controllers\Controller;

use App\Models\QuemSomos;

class QuemSomosController extends Controller
{
    public function index()
    {
        $registro = QuemSomos::first();

        return view('painel.quem-somos.edit', compact('registro'));
    }

    public function update(QuemSomosRequest $request, QuemSomos $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = QuemSomos::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.quem-somos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/tecnologias/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Tecnologias /</small> Adicionar Tecnologia</h2>
    </legend>

    {!! Form::open(['route' => 'painel.tecnologias.store', 'files' => true]) !!}

        @include('painel.tecnologias.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/tecnologias/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Tecnologias /</small> Editar Tecnologia</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.tecnologias.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.tecnologias.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/tecnologias/form.blade.php
@include('painel.common.flash')

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_pt', 'Título PT') !!}
            {!! Form::text('titulo_pt', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('texto_pt', 'Texto PT') !!}
            {!! Form::textarea('texto_pt', null, ['class' => 'form-control ckeditor', 'data-editor' => 'basic']) !!}
        </div>
        <div class="well form-group">
            {!! Form::label('infografico_pt', 'Infográfico PT (largura máxima: 650px)') !!}
        @if($submitText == 'Alterar')
            <img src="{{ url('assets/img/tecnologias/infografico/'.$registro->infografico_pt) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
        @endif
            {!! Form::file('infografico_pt', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_en', 'Título EN') !!}
            {!! Form::text('titulo_en', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('texto_en', 'Texto EN') !!}
            {!! Form::textarea('texto_en', null, ['class' => 'form-control ckeditor', 'data-editor' => 'basic']) !!}
        </div>
        <div class="well form-group">
            {!! Form::label('infografico_en', 'Infográfico EN (largura máxima: 650px)') !!}
        @if($submitText == 'Alterar')
            <img src="{{ url('assets/img/tecnologias/infografico/'.$registro->infografico_en) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
        @endif
            {!! Form::file('infografico_en', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_es', 'Título ES') !!}
            {!! Form::text('titulo_es', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('texto_es', 'Texto ES') !!}
            {!! Form::textarea('texto_es', null, ['class' => 'form-control ckeditor', 'data-editor' => 'basic']) !!}
        </div>
        <div class="well form-group">
            {!! Form::label('infografico_es', 'Infográfico ES (largura máxima: 650px)') !!}
        @if($submitText == 'Alterar')
            <img src="{{ url('assets/img/tecnologias/infografico/'.$registro->infografico_es) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
        @endif
            {!! Form::file('infografico_es', ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem lateral') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/tecnologias/imagem-lateral/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.tecnologias.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/tecnologias/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Tecnologias
            <a href="{{ route('painel.tecnologias.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Tecnologia</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="tecnologias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título PT</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo_pt }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.tecnologias.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.tecnologias.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection