laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('a-empresa/{slug?}', 'EmpresaController@index')->name('empresa');
    Route::get('areas-de-atuacao/{areaDeAtuacao?}', 'AreasDeAtuacaoController@index')->name('areas-de-atuacao');
    Route::get('responsabilidade-social', 'ResponsabilidadeSocialController@index')->name('responsabilidade-social');
    Route::get('tecnologias/{tecnologia?}', 'TecnologiasController@index')->name('tecnologias');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe-conosco');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en' || $idioma == 'es') {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('trabalhe-conosco', 'TrabalheConoscoController', ['only' => ['index', 'update']]);
		Route::resource('tecnologias', 'TecnologiasController');
        Route::resource('areas-de-atuacao', 'AreasDeAtuacaoController');
		Route::resource('areas-de-atuacao.subcategorias', 'AreasDeAtuacaoSubcategoriasController');
		Route::resource('responsabilidade-social', 'ResponsabilidadeSocialController', ['only' => ['index', 'update']]);
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
		Route::resource('missao-e-visao', 'MissaoEVisaoController', ['only' => ['index', 'update']]);
		Route::resource('garantia-de-qualidade', 'GarantiaDeQualidadeController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
        Route::resource('newsletter', 'NewsletterController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AreasDeAtuacaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeAtuacaoRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeAtuacao;

class AreasDeAtuacaoController extends Controller
{
    public function index()
    {
        $registros = AreaDeAtuacao::ordenados()->get();

        return view('painel.areas-de-atuacao.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.areas-de-atuacao.create');
    }

    public function store(AreasDeAtuacaoRequest $request)
    {
        try {

            $input = $request->all();
            $input['capa'] = AreaDeAtuacao::uploadCapa();
            $input['imagem'] = AreaDeAtuacao::uploadImagem();

            AreaDeAtuacao::create($input);
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeAtuacao $registro)
    {
        return view('painel.areas-de-atuacao.edit', compact('registro'));
    }

    public function update(AreasDeAtuacaoRequest $request, AreaDeAtuacao $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['capa'])) $input['capa'] = AreaDeAtuacao::uploadCapa();
            if (isset($input['imagem'])) $input['imagem'] = AreaDeAtuacao::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeAtuacao $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.areas-de-atuacao.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AreasDeAtuacaoSubcategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AreasDeAtuacaoSubcategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\AreaDeAtuacao;
use App\Models\AreaDeAtuacaoSubcategoria;

class AreasDeAtuacaoSubcategoriasController extends Controller
{
    public function index(AreaDeAtuacao $areaDeAtuacao)
    {
        $registros = AreaDeAtuacaoSubcategoria::area($areaDeAtuacao->id)
            ->ordenados()->get();

        return view('painel.areas-de-atuacao.subcategorias.index', compact('areaDeAtuacao', 'registros'));
    }

    public function create(AreaDeAtuacao $areaDeAtuacao)
    {
        return view('painel.areas-de-atuacao.subcategorias.create', compact('areaDeAtuacao'));
    }

    public function store(AreaDeAtuacao $areaDeAtuacao, AreasDeAtuacaoSubcategoriasRequest $request)
    {
        try {

            $input = $request->all();

            $areaDeAtuacao->subcategorias()->create($input);

            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        return view('painel.areas-de-atuacao.subcategorias.edit', compact('areaDeAtuacao', 'registro'));
    }

    public function update(AreasDeAtuacaoSubcategoriasRequest $request, AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);
            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(AreaDeAtuacao $areaDeAtuacao, AreaDeAtuacaoSubcategoria $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.areas-de-atuacao.subcategorias.index', $areaDeAtuacao->id)->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = Banner::uploadImagem();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = Banner::uploadImagem();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/GarantiaDeQualidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\GarantiaDeQualidadeRequest;
use App\Http\Controllers\Controller;

use App\Models\GarantiaDeQualidade;

class GarantiaDeQualidadeController extends Controller
{
    public function index()
    {
        $registro = GarantiaDeQualidade::first();

        return view('painel.garantia-de-qualidade.edit', compact('registro'));
    }

    public function update(GarantiaDeQualidadeRequest $request, GarantiaDeQualidade $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = GarantiaDeQualidade::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.garantia-de-qualidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/MissaoEVisaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\MissaoEVisaoRequest;
use App\Http\Controllers\Controller;

use App\Models\MissaoEVisao;

class MissaoEVisaoController extends Controller
{
    public function index()
    {
        $registro = MissaoEVisao::first();

        return view('painel.missao-e-visao.edit', compact('registro'));
    }

    public function update(MissaoEVisaoRequest $request, MissaoEVisao $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = MissaoEVisao::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.missao-e-visao.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/NewsletterController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Newsletter;

class NewsletterController extends Controller
{
    public function index()
    {
        $emails = Newsletter::orderBy('email', 'ASC')->paginate(20);

        return view('painel.newsletter.index', compact('emails'));
    }

    public function destroy(Newsletter $email)
    {
        try {

            $email->delete();
            return redirect()->route('painel.newsletter.index')->with('success', 'E-mail excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir e-mail: '.$e->getMessage()]);

        }
    }

    public function exportar()
    {
        $file = 'liotecnica-newsletter_'.date('d-m-Y_His');

        \Excel::create($file, function($excel) {
            $excel->sheet('emails', function($sheet) {
                $sheet->fromModel(Newsletter::orderBy('email', 'ASC')->get(['nome', 'email']));
            });
        })->download('csv');
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use App\Helpers\CropImage;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/areas-de-atuacao/imagens/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }

}

laravel/app/Http/Controllers/Painel/QuemSomosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\QuemSomosRequest;
use App\Http\Controllers\Controller;

use App\Models\QuemSomos;

class QuemSomosController extends Controller
{
    public function index()
    {
        $registro = QuemSomos::first();

        return view('painel.quem-somos.edit', compact('registro'));
    }

    public function update(QuemSomosRequest $request, QuemSomos $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = QuemSomos::uploadImagem();

            $registro->update($input);

            return redirect()->route('painel.quem-somos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
    <li class="dropdown @if(str_is('painel.quem-somos*', Route::currentRouteName()) || str_is('painel.missao-e-visao*', Route::currentRouteName()) || str_is('painel.garantia-de-qualidade*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            A Empresa
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.quem-somos.index') }}">Quem Somos</a></li>
            <li><a href="{{ route('painel.missao-e-visao.index') }}">Missão e Visão</a></li>
            <li><a href="{{ route('painel.garantia-de-qualidade.index') }}">Garantia de Qualidade</a></li>
        </ul>
    </li>
    <li @if(str_is('painel.areas-de-atuacao*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.areas-de-atuacao.index') }}">Áreas de Atuação</a>
    </li>
    <li @if(str_is('painel.responsabilidade-social*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.responsabilidade-social.index') }}">Responsabilidade Social</a>
    </li>
	<li @if(str_is('painel.tecnologias*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.tecnologias.index') }}">Tecnologias</a>
	</li>
    <li @if(str_is('painel.trabalhe-conosco*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.trabalhe-conosco.index') }}">Trabalhe Conosco</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.newsletter*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">Newsletter</a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/jscolor.min.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>